#!/bin/sh

COWS=(`cowsay -l | sed -e '1d'`)
I=`expr $RANDOM % ${#COWS[@]}`

ARGS=("-b" "-d" "-g" "-p" "-s" "-t" "-w" "-y")
J=`expr $RANDOM % ${#ARGS[@]}`

NAMES=("jingletron" "jangletron")
K=`expr $RANDOM % ${#NAMES[@]}`

echo "Thus spake the ${NAMES[$K]}:"
fortune -a | cowsay -W 50 -f ${COWS[$I]} ${ARGS[$J]} | sed -e 's/^/  /'
