#!/usr/bin/env zsh

COWS=(`cowsay -l | sed -e '1d'`)
I=`expr $RANDOM % $#COWS[@] + 1`

ARGS=("-b" "-d" "-g" "-p" "-s" "-t" "-w" "-y")
J=`expr $RANDOM % $#ARGS[@]`

NAMES=("jingletron" "jangletron")
K=`expr $RANDOM % $#NAMES[@] + 1`

echo "Thus spake the $NAMES[$K]:"
fortune -a | cowsay -W 60 -f $COWS[$I] $ARGS[$J]
